# Optional[str] Model load weights from path.
pretrained: null
# [ResNet, VGG, RCNN, SimpleNet]
backbone: SimpleNet
# [LSTM]
sequence: BiLSTM
# [AvgPool] factor should be selected manually.
# Depend on backbone output.
pool: {name: AvgPool, factor: 6}
# [CTC]
prediction: CTC
input_channel: 3
output_channel: 512
hidden_size: 256
num_class: 2
num_fiducial: 20