# [train, eval, inference]
mode: train
device: cpu
epoch: 50
batch_size: 64
num_workers: 0
project_path: ./
# [CTC, CE]
loss_function: CTC
# [accuracy_char, accuracy_word]
metrics: {types: [accuracy_char, accuracy_word],
          threshold: 0.5}
main_metrics: [accuracy_word]
# [Adam, SGD, Adadelta]
optimizer: {name: Adam, lr: 0.0001}
# [LinearLR, LambdaLR, None]
scheduler: {'name': 'LinearLR', factor: 1.0}
# early stopping patience
patience: 10
